# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4950229c0add6ce5108e2902fdc8f5c5eeeb79254ea69f7a2df6f00e9b6e440b635f030b94f5e8c3159c09912b14b68d0e5e62013f47ab7d76e6acbd89036039

test:
  secret_key_base: eb6abf4389e926555343be36a8128f882e4e664156dbd4d51c24b6df7fc6095c07435756de598979d725d17827281e302f9c5f0226b053117a26680701a00281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
